### ISSUE TITLE
Cannot build CentOS 5

### ISSUE THREAD

**Issue by jkugler** [grtjn/centos-packer-templates#3]
Trying to build the CentOS 5.11 box so I can contribute a change to fix #2. However:
```
± packer build -only=virtualbox-iso centos-5.11-x86_64.json 
virtualbox-iso output will be in this color.

1 error(s) occurred:

* Bad source 'floppy/dummy_metadata.json': stat floppy/dummy_metadata.json: no such file or directory
```
I'm not sure what it is looking for. There isn't anything in the README or CONTRIBUTING about what might need to be set up or created.  Any tips would be great! Thanks!

**Comment by jkugler** [comment]
I have reworked the centos-5.11-x86_64.json file to work in the context of the current bento system. Would you like a pull request for this? Or are you still building images?

**Comment by grtjn** [comment]
As I mentioned in the other ticket, I never really tried (re)building images myself. I've always copied the templates for posterity, and also use Vagrant to repackage the images built by the Chef Bento team.

For any detailed questions regarding the templates, I'd recommend reaching out to https://github.com/chef/bento. The old packer files have been replaced long since (they only keep latest), but there are likely people around that might remember..

I'd welcome a PR. I won't do much with the packer files myself, but it may help others who are looking at building images themselves..

**Comment by jkugler** [comment]
I realized I needed to build this in the context of the bento repository, with modifications. I figured it out. Thank you!
